[connections.default]
account = "${SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT}"
user = "${SNOWFLAKE_CONNECTIONS_DEFAULT_USER}"
password = "${SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD}"
database = "${SNOWFLAKE_CONNECTIONS_DEFAULT_DATABASE}"
warehouse = "${SNOWFLAKE_CONNECTIONS_DEFAULT_WAREHOUSE}"
role = "${SNOWFLAKE_CONNECTIONS_DEFAULT_ROLE}"
schema = "${SNOWFLAKE_CONNECTIONS_DEFAULT_SCHEMA}"
